// app/components/templates/modern/sections/ProjectSection.vue
<template>
  <section class="modern-projects">
    <SectionTitle
      :title="t('resume.sections.projects')"
      :global-settings="globalSettings"
      :theme-color="themeColor"
    />
    <div class="project-list">
      <div
        v-for="proj in visibleProjects"
        :key="proj.id"
        class="project-item"
        :style="itemStyle"
      >
        <div class="project-header">
          <span class="name">{{ proj.name }}</span>
          <span v-if="proj.date" class="date">{{ proj.date }}</span>
        </div>
        <div v-if="proj.role" class="role">{{ proj.role }}</div>
        <div
          v-if="proj.description"
          class="description rich-content"
          v-html="proj.description"
        ></div>
        <a
          v-if="proj.link"
          :href="proj.link"
          class="project-link"
          target="_blank"
          rel="noopener noreferrer"
        >
          {{ proj.linkLabel || proj.link }}
        </a>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import type { Project, GlobalSettings } from '#shared/types/resume'
import type { ResumeTemplate } from '#shared/types/template'
import SectionTitle from './SectionTitle.vue'

// 项目经历模块
const props = defineProps<{
  projects: Project[]
  globalSettings?: GlobalSettings
  template: ResumeTemplate
}>()

const { t } = useI18n()

const themeColor = computed(
  () => props.globalSettings?.themeColor || props.template.colorScheme.primary
)

const visibleProjects = computed(() =>
  (props.projects || []).filter((p) => p.visible !== false)
)

const itemStyle = computed(() => ({
  marginBottom: `${props.template.spacing.itemGap}px`,
}))

const subheaderSize = computed(() => props.globalSettings?.subheaderSize || 16)
const baseFontSize = computed(() => props.globalSettings?.baseFontSize || 16)
</script>

<style scoped>
.project-list {
  display: flex;
  flex-direction: column;
}

.project-item {
  position: relative;
  padding-left: 16px;
  border-left: 2px solid #e2e8f0;
}

.project-item::before {
  content: '';
  position: absolute;
  left: -5px;
  top: 6px;
  width: 8px;
  height: 8px;
  border-radius: 50%;
  background: #0f172a;
}

.project-header {
  display: flex;
  justify-content: space-between;
  align-items: baseline;
  gap: 12px;
}

.name {
  font-size: v-bind('`${subheaderSize}px`');
  font-weight: 700;
  color: v-bind('themeColor');
}

.date {
  font-size: v-bind('`${baseFontSize - 2}px`');
  color: #64748b;
  flex-shrink: 0;
}

.role {
  font-size: v-bind('`${baseFontSize}px`');
  font-weight: 500;
  color: #1e293b;
  margin-top: 2px;
  margin-bottom: 4px;
}

.description {
  color: #475569;
  font-size: v-bind('`${baseFontSize - 1}px`');
}

.project-link {
  display: inline-block;
  margin-top: 4px;
  font-size: 12px;
  color: #0f172a;
  text-decoration: underline;
  word-break: break-all;
}

.rich-content :deep(ul) {
  list-style: none;
  padding-left: 0;
  margin: 4px 0;
}

.rich-content :deep(ul li) {
  position: relative;
  padding-left: 16px;
  margin-bottom: 2px;
}

.rich-content :deep(ul li::before) {
  content: '';
  position: absolute;
  left: 4px;
  top: 0.55em;
  width: 6px;
  height: 6px;
  border-radius: 50%;
  background-color: currentColor;
}

.rich-content :deep(ol) {
  list-style: none;
  padding-left: 0;
  margin: 4px 0;
  counter-reset: item;
}

.rich-content :deep(ol li) {
  position: relative;
  padding-left: 20px;
  margin-bottom: 2px;
  counter-increment: item;
}

.rich-content :deep(ol li::before) {
  content: counter(item) '.';
  position: absolute;
  left: 0;
  font-weight: 600;
}
</style>

// src/components/templates/professional/sections/ProjectSection.tsx
'use client'

import { useMemo } from 'react'
import messages from '@/messages/zh.json'
import type { Project, GlobalSettings } from '@/shared/types/resume'
import type { ResumeTemplate } from '@/shared/types/template'
import { SectionTitle } from './SectionTitle'

interface ProjectSectionProps {
  projects: Project[]
  globalSettings?: GlobalSettings
  template: ResumeTemplate
}

export function ProjectSection({ projects, globalSettings, template }: ProjectSectionProps) {
  const t = messages
  const visibleProjects = useMemo(() => (projects || []).filter(p => p.visible !== false), [projects])
  const themeColor = globalSettings?.themeColor || template.colorScheme.primary
  const subheaderSize = globalSettings?.subheaderSize || 16
  const baseFontSize = globalSettings?.baseFontSize || 16
  const sectionSpacing = globalSettings?.sectionSpacing || 10

  const sectionStyle = useMemo(() => ({ marginBottom: `${sectionSpacing}px` }), [sectionSpacing])
  const itemStyle = useMemo(() => ({ marginBottom: `${template.spacing.itemGap}px` }), [template.spacing.itemGap])

  return (
    <section style={sectionStyle}>
      <SectionTitle title={t.resume.sections.projects} globalSettings={globalSettings} />
      <div>
        {visibleProjects.map(proj => (
          <div key={proj.id} style={itemStyle}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', gap: 12 }}>
              <span style={{ fontSize: subheaderSize, fontWeight: 700, color: themeColor }}>{proj.name}</span>
              {proj.date && <span style={{ fontSize: baseFontSize - 2, color: template.colorScheme.secondary }}>{proj.date}</span>}
            </div>
            {proj.role && (
              <div style={{ fontSize: baseFontSize, color: template.colorScheme.text, marginTop: 2 }}>{proj.role}</div>
            )}
            {proj.description && <div className="rich-content" dangerouslySetInnerHTML={{ __html: proj.description }} />}
            {proj.link && (
              <a href={proj.link} target="_blank" rel="noopener noreferrer" style={{ color: themeColor, fontSize: baseFontSize - 1 }}>
                {proj.linkLabel || proj.link}
              </a>
            )}
          </div>
        ))}
      </div>
    </section>
  )
}
