// app/components/editor/project/ProjectPanel.vue
<template>
  <div class="p-4 space-y-3">
    <div class="flex items-center justify-between">
      <h3 class="text-base font-medium">项目经历</h3>
      <t-button theme="primary" @click="add">
        <Plus class="w-4 h-4 mr-1" /> 添加
      </t-button>
    </div>

    <draggable
      v-model="list"
      :item-key="(item: Project) => item.id"
      handle=".drag-handle"
      ghost-class="opacity-50"
      @end="onDragEnd"
    >
      <template #item="{ element }">
        <ProjectItem
          :project="element"
          @update="(data) => update(element.id, data)"
          @remove="remove(element.id)"
        />
      </template>
    </draggable>

    <div v-if="list.length === 0" class="text-center py-8 text-gray-400 border border-dashed rounded">
      暂无项目经历，点击右上角添加
    </div>
  </div>
</template>

<script setup lang="ts">
import draggable from 'vuedraggable'
import type { Project } from '#shared/types/resume'
import { Plus } from 'lucide-vue-next'
import { useResumeStore } from '~/stores/resume'

const resumeStore = useResumeStore()

const list = computed({
  get: () => resumeStore.activeResume?.projects || [],
  set: (val: Project[]) => {
    if (!resumeStore.activeResumeId) return
    resumeStore.importResume(resumeStore.activeResumeId, { projects: val })
  },
})

const onDragEnd = () => {
  // 由 v-model 自动同步
}

const add = () => {
  if (!resumeStore.activeResumeId) return
  resumeStore.addProject(resumeStore.activeResumeId, {
    name: '',
    role: '',
    date: '',
    description: '',
    visible: true,
  })
}

const update = (id: string, data: Partial<Project>) => {
  if (!resumeStore.activeResumeId) return
  resumeStore.updateProject(resumeStore.activeResumeId, id, data)
}

const remove = (id: string) => {
  if (!resumeStore.activeResumeId) return
  resumeStore.removeProject(resumeStore.activeResumeId, id)
}
</script>

// src/components/editor/projects/ProjectPanel.tsx
'use client'

import { useCallback } from 'react'
import { Button } from 'antd'
import { Plus } from 'lucide-react'
import { useResumeStore, selectActiveResume } from '@/stores/resume-store'
import type { Project } from '@/shared/types/resume'
import { ProjectItem } from './ProjectItem'

export function ProjectPanel() {
  const activeResume = useResumeStore(selectActiveResume)
  const activeResumeId = useResumeStore((s) => s.activeResumeId)
  const addProject = useResumeStore((s) => s.addProject)
  const updateProject = useResumeStore((s) => s.updateProject)
  const removeProject = useResumeStore((s) => s.removeProject)

  const projects = (activeResume?.projects || []).filter(
    (p) => p.visible !== false
  )

  const handleAdd = useCallback(() => {
    if (!activeResumeId) return
    addProject(activeResumeId, {
      name: '',
      role: '',
      date: '',
      description: '',
      visible: true,
    })
  }, [activeResumeId, addProject])

  const handleChange = useCallback(
    (id: string, data: Partial<Project>) => {
      if (!activeResumeId) return
      updateProject(activeResumeId, id, data)
    },
    [activeResumeId, updateProject]
  )

  const handleDelete = useCallback(
    (id: string) => {
      if (!activeResumeId) return
      removeProject(activeResumeId, id)
    },
    [activeResumeId, removeProject]
  )

  return (
    <div className="p-4 space-y-4">
      <h3 className="text-base font-medium">项目经历</h3>
      <div className="space-y-3">
        {projects.map((proj) => (
          <ProjectItem
            key={proj.id}
            item={proj}
            onChange={handleChange}
            onDelete={handleDelete}
          />
        ))}
      </div>
      <Button
        type="dashed"
        block
        onClick={handleAdd}
        icon={<Plus className="w-4 h-4" />}
      >
        添加项目经历
      </Button>
    </div>
  )
}
