// app/pages/dashboard/templates.vue
<template>
  <div class="templates-page p-8 max-w-5xl mx-auto">
    <div class="flex items-center justify-between mb-6">
      <h1 class="text-2xl font-bold">{{ t('nav.templates') }}</h1>
      <t-button theme="default" variant="outline" @click="goBack">
        <ArrowLeft class="w-4 h-4 mr-1" />
        {{ t('common.back') }}
      </t-button>
    </div>

    <!-- 当前激活简历提示 -->
    <div v-if="activeResume" class="mb-4 text-sm text-gray-500">
      {{ t('templates.currentTemplate') }}：
      <t-tag theme="primary" variant="light" size="small">
        {{ currentTemplateName }}
      </t-tag>
    </div>

    <!-- 模板网格 -->
    <div class="grid grid-cols-2 md:grid-cols-3 gap-4">
      <div
        v-for="tpl in templates"
        :key="tpl.config.id"
        class="template-card border rounded-lg overflow-hidden cursor-pointer transition-all hover:shadow-md"
        :class="{
          'border-primary ring-2 ring-primary/30': isSelected(tpl.config.id),
          'border-[hsl(var(--border))]': !isSelected(tpl.config.id),
        }"
        @click="selectTemplate(tpl.config.id)"
      >
        <!-- 缩略图占位（渐变背景 + LayoutTemplate 图标） -->
        <div
          class="aspect-[3/4] bg-gradient-to-br from-gray-50 to-gray-200 flex items-center justify-center"
        >
          <div class="text-gray-400 text-sm text-center">
            <LayoutTemplate class="w-8 h-8 mx-auto mb-2" />
            {{ tpl.config.name }}
          </div>
        </div>
        <!-- 名称、描述与主色调 -->
        <div class="p-3">
          <div class="flex items-center justify-between mb-1">
            <h4 class="text-sm font-medium">{{ tpl.config.name }}</h4>
            <t-tag v-if="isSelected(tpl.config.id)" theme="primary" size="small">
              {{ t('templates.currentTemplate') }}
            </t-tag>
          </div>
          <p class="text-xs text-gray-500 line-clamp-2 mb-2">
            {{ tpl.config.description }}
          </p>
          <div class="flex items-center gap-1">
            <span
              class="inline-block w-3 h-3 rounded-full border border-gray-200"
              :style="{ backgroundColor: tpl.config.colorScheme.primary }"
            />
            <span
              class="inline-block w-3 h-3 rounded-full border border-gray-200"
              :style="{ backgroundColor: tpl.config.colorScheme.secondary }"
            />
            <span
              class="inline-block w-3 h-3 rounded-full border border-gray-200"
              :style="{ backgroundColor: tpl.config.colorScheme.text }"
            />
          </div>
        </div>
      </div>
    </div>

    <!-- 无激活简历时的提示 -->
    <div v-if="!activeResume" class="text-center py-12 text-gray-400">
      <LayoutTemplate class="w-10 h-10 mx-auto mb-3" />
      <p>{{ t('resume.empty') }}</p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ArrowLeft, LayoutTemplate } from 'lucide-vue-next'
import { MessagePlugin } from 'tdesign-vue-next'
import { TEMPLATE_REGISTRY } from '~/components/templates/registry'
import { useResumeStore } from '~/stores/resume'

definePageMeta({
  layout: 'app',
})

const { t } = useI18n()
const router = useRouter()
const localePath = useLocalePath()
const resumeStore = useResumeStore()

// 所有可用模板
const templates = TEMPLATE_REGISTRY

// 当前激活简历
const activeResume = computed(() => resumeStore.activeResume)

// 当前模板名称
const currentTemplateName = computed(() => {
  const id = activeResume.value?.templateId
  if (!id) return ''
  return templates.find((tpl) => tpl.config.id === id)?.config.name ?? ''
})

// 判断是否为当前选中模板
const isSelected = (id: string) => {
  return activeResume.value?.templateId === id
}

// 切换模板
const selectTemplate = (templateId: string) => {
  const resumeId = resumeStore.activeResumeId
  if (!resumeId) return
  if (isSelected(templateId)) return
  resumeStore.setTemplateId(resumeId, templateId)
  MessagePlugin.success(t('templates.switchSuccess'))
}

// 返回控制台
const goBack = () => {
  router.push(localePath('/dashboard'))
}

// 初始化
onMounted(() => {
  resumeStore.initialize()
})

useHead({ title: `${t('nav.templates')} - 自由简历` })
</script>

<style scoped>
.template-card {
  background-color: hsl(var(--card));
}
.line-clamp-2 {
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
</style>

// src/app/dashboard/templates/page.tsx
'use client'

import { useEffect } from 'react'
import { Button, message } from 'antd'
import messages from '@/messages/zh.json'
import { TEMPLATE_REGISTRY } from '@/components/templates/registry'
import { useResumeStore, selectActiveResume } from '@/stores/resume-store'
import { LandingHeader } from '@/components/home/LandingHeader'

const t = messages

export default function DashboardTemplatesPage() {
  const activeResume = useResumeStore(selectActiveResume)
  const setTemplateId = useResumeStore(s => s.setTemplateId)
  const initialize = useResumeStore(s => s.initialize)

  useEffect(() => { initialize() }, [])

  const handleSelect = (templateId: string) => {
    if (!activeResume) return
    setTemplateId(activeResume.id, templateId)
    message.success(t.templates.switchSuccess)
  }

  return (
    <div className="min-h-screen bg-[hsl(var(--bg-base))]">
      <LandingHeader />
      <div className="p-8 max-w-5xl mx-auto">
        <h1 className="text-2xl font-bold mb-6">{t.templates.selectTemplate}</h1>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {TEMPLATE_REGISTRY.map(entry => (
            <div key={entry.config.id} className={`rounded-xl border p-6 cursor-pointer transition-all duration-200 hover:shadow-md ${activeResume?.templateId === entry.config.id ? 'border-[hsl(var(--brand))] bg-[hsl(var(--brand-light))]' : 'border-[hsl(var(--border-default))] bg-[hsl(var(--bg-card))]'}`} onClick={() => handleSelect(entry.config.id)}>
              <div className="h-40 rounded-lg mb-4 flex items-center justify-center" style={{ background: `linear-gradient(135deg, ${entry.config.colorScheme.primary}22, ${entry.config.colorScheme.background})` }}>
                <span className="text-4xl opacity-30">{entry.config.name.charAt(0)}</span>
              </div>
              <h3 className="font-semibold text-[hsl(var(--text-primary))]">{entry.config.name}</h3>
              <p className="text-sm text-[hsl(var(--text-secondary))] mt-1">{entry.config.description}</p>
              <div className="flex gap-1 mt-3">
                {[entry.config.colorScheme.primary, entry.config.colorScheme.secondary, entry.config.colorScheme.text].map((c, i) => <span key={i} className="w-5 h-5 rounded-full border border-[hsl(var(--border-default))]" style={{ backgroundColor: c }} />)}
              </div>
              {activeResume?.templateId === entry.config.id && <Button type="primary" size="small" className="mt-3 w-full">{t.templates.currentTemplate}</Button>}
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}
