// app/components/editor/education/EducationPanel.vue
<template>
  <div class="p-4 space-y-3">
    <div class="flex items-center justify-between">
      <h3 class="text-base font-medium">教育经历</h3>
      <t-button theme="primary" @click="add">
        <Plus class="w-4 h-4 mr-1" /> 添加
      </t-button>
    </div>

    <draggable
      v-model="list"
      :item-key="(item: Education) => item.id"
      handle=".drag-handle"
      ghost-class="opacity-50"
      @end="onDragEnd"
    >
      <template #item="{ element }">
        <EducationItem
          :education="element"
          @update="(data) => update(element.id, data)"
          @remove="remove(element.id)"
        />
      </template>
    </draggable>

    <div v-if="list.length === 0" class="text-center py-8 text-gray-400 border border-dashed rounded">
      暂无教育经历，点击右上角添加
    </div>
  </div>
</template>

<script setup lang="ts">
import draggable from 'vuedraggable'
import type { Education } from '#shared/types/resume'
import { Plus } from 'lucide-vue-next'
import { useResumeStore } from '~/stores/resume'

const resumeStore = useResumeStore()

// 从 store 派生的可排序列表
const list = computed({
  get: () => resumeStore.activeResume?.education || [],
  set: (val: Education[]) => {
    if (!resumeStore.activeResumeId) return
    // 通过 importResume 替换整个 education 数组以保留顺序
    resumeStore.importResume(resumeStore.activeResumeId, { education: val })
  },
})

const onDragEnd = () => {
  // 由 v-model 自动同步
}

const add = () => {
  if (!resumeStore.activeResumeId) return
  resumeStore.addEducation(resumeStore.activeResumeId, {
    school: '',
    major: '',
    degree: '',
    startDate: '',
    endDate: '',
    gpa: '',
    description: '',
    visible: true,
  })
}

const update = (id: string, data: Partial<Education>) => {
  if (!resumeStore.activeResumeId) return
  resumeStore.updateEducation(resumeStore.activeResumeId, id, data)
}

const remove = (id: string) => {
  if (!resumeStore.activeResumeId) return
  resumeStore.removeEducation(resumeStore.activeResumeId, id)
}
</script>

// src/components/editor/education/EducationPanel.tsx
'use client'

import { useCallback } from 'react'
import { Button } from 'antd'
import { Plus } from 'lucide-react'
import { useResumeStore, selectActiveResume } from '@/stores/resume-store'
import type { Education } from '@/shared/types/resume'
import { EducationItem } from './EducationItem'

export function EducationPanel() {
  const activeResume = useResumeStore(selectActiveResume)
  const activeResumeId = useResumeStore((s) => s.activeResumeId)
  const addEducation = useResumeStore((s) => s.addEducation)
  const updateEducation = useResumeStore((s) => s.updateEducation)
  const removeEducation = useResumeStore((s) => s.removeEducation)

  const educationItems = (activeResume?.education || []).filter(
    (e) => e.visible !== false
  )

  const handleAdd = useCallback(() => {
    if (!activeResumeId) return
    addEducation(activeResumeId, {
      school: '',
      major: '',
      degree: '',
      startDate: '',
      endDate: '',
      visible: true,
    })
  }, [activeResumeId, addEducation])

  const handleChange = useCallback(
    (id: string, data: Partial<Education>) => {
      if (!activeResumeId) return
      updateEducation(activeResumeId, id, data)
    },
    [activeResumeId, updateEducation]
  )

  const handleDelete = useCallback(
    (id: string) => {
      if (!activeResumeId) return
      removeEducation(activeResumeId, id)
    },
    [activeResumeId, removeEducation]
  )

  return (
    <div className="p-4 space-y-4">
      <h3 className="text-base font-medium">教育经历</h3>
      <div className="space-y-3">
        {educationItems.map((edu) => (
          <EducationItem
            key={edu.id}
            item={edu}
            onChange={handleChange}
            onDelete={handleDelete}
          />
        ))}
      </div>
      <Button
        type="dashed"
        block
        onClick={handleAdd}
        icon={<Plus className="w-4 h-4" />}
      >
        添加教育经历
      </Button>
    </div>
  )
}
