// app/components/preview/ResumePreview.vue
<template>
  <div class="resume-preview-container">
    <component
      :is="TemplateComponent"
      v-if="TemplateComponent"
      :data="resumeData"
      :template="templateConfig"
    />
    <div v-else class="flex items-center justify-center h-64 text-[hsl(var(--text-tertiary))]">
      请选择模板
    </div>
  </div>
</template>

<script setup lang="ts">
import type { ResumeData } from '#shared/types/resume'
import {
  getTemplateComponent,
  getTemplateConfig,
} from '~/components/templates/registry'
import { professionalConfig } from '~/components/templates/professional/config'

// 简历预览容器：根据当前模板从 registry 获取组件并渲染
const props = defineProps<{
  resumeData: ResumeData
}>()

// 当前模板配置（默认 professional）
const templateConfig = computed(() => {
  const id = props.resumeData.templateId
  return (id && getTemplateConfig(id)) || professionalConfig
})

// 当前模板组件
const TemplateComponent = computed(() => {
  return getTemplateComponent(templateConfig.value.layout)
})
</script>

<style scoped>
.resume-preview-container {
  width: 100%;
  min-height: 100%;
}
</style>

// src/components/preview/ResumePreview.tsx
'use client'

import { getTemplateComponent, getTemplateConfig } from '@/components/templates/registry'
import { professionalConfig } from '@/components/templates/professional/config'
import type { ResumeData } from '@/shared/types/resume'

interface ResumePreviewProps {
  resumeData: ResumeData
}

export function ResumePreview({ resumeData }: ResumePreviewProps) {
  const templateId = resumeData.templateId
  const templateConfig = (templateId && getTemplateConfig(templateId)) || professionalConfig
  const TemplateComponent = getTemplateComponent(templateConfig.layout)

  if (!TemplateComponent) {
    return (
      <div className="flex items-center justify-center h-64 text-[hsl(var(--text-tertiary))]">
        请选择模板
      </div>
    )
  }

  return (
    <div id="resume-preview" className="resume-preview-container">
      <TemplateComponent data={resumeData} template={templateConfig} />
    </div>
  )
}
