// app/components/home/Footer.vue
<template>
  <footer class="border-t border-[hsl(var(--border-default))]/60 bg-[hsl(var(--bg-card))]/50 backdrop-blur-sm">
    <div class="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8">
      <div class="flex flex-col items-center justify-between gap-6 sm:flex-row">
        
        <div class="flex items-center gap-2">
          <span
            class="flex h-7 w-7 items-center justify-center rounded-[8px] bg-[hsl(var(--brand))] text-[hsl(var(--text-inverse))]"
            style="box-shadow: var(--shadow-sm)"
          >
            <FileText class="h-4 w-4" />
          </span>
          <span class="text-[15px] font-semibold text-[hsl(var(--text-primary))]">
            {{ t('common.appName') }}
          </span>
        </div>

        
        <nav class="flex items-center gap-6 text-[13px]">
          <a
            href="https://github.com"
            target="_blank"
            rel="noopener noreferrer"
            class="flex items-center gap-1.5 text-[hsl(var(--text-secondary))] transition-colors duration-200 hover:text-[hsl(var(--text-primary))]"
          >
            <Github class="h-[15px] w-[15px]" />
            {{ t('landing.footer.links.github') }}
          </a>
          <a
            href="#"
            class="text-[hsl(var(--text-secondary))] transition-colors duration-200 hover:text-[hsl(var(--text-primary))]"
          >
            {{ t('landing.footer.links.privacy') }}
          </a>
          <a
            href="#"
            class="text-[hsl(var(--text-secondary))] transition-colors duration-200 hover:text-[hsl(var(--text-primary))]"
          >
            {{ t('landing.footer.links.terms') }}
          </a>
        </nav>
      </div>

      
      <div class="mt-8 border-t border-[hsl(var(--border-default))]/50 pt-8 text-center">
        <p class="text-[13px] text-[hsl(var(--text-secondary))]">
          {{ t('landing.footer.copyright') }}
        </p>
      </div>
    </div>
  </footer>
</template>

<script setup lang="ts">
import { FileText, Github } from 'lucide-vue-next'

const { t } = useI18n()
</script>

// src/components/home/Footer.tsx
'use client'

import { FileText } from 'lucide-react'
import { useTranslations } from 'next-intl'

export function Footer() {
  const t = useTranslations()

  return (
    <footer className="border-t border-[hsl(var(--border-default))]/60 bg-[hsl(var(--bg-card))]/50 backdrop-blur-sm">
      <div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8">
        <div className="flex flex-col items-center justify-between gap-6 sm:flex-row">
          <div className="flex items-center gap-2">
            <span
              className="flex h-7 w-7 items-center justify-center rounded-[8px] bg-[hsl(var(--brand))] text-[hsl(var(--text-inverse))]"
              style={{ boxShadow: 'var(--shadow-sm)' }}
            >
              <FileText className="h-4 w-4" />
            </span>
            <span className="text-[15px] font-semibold text-[hsl(var(--text-primary))]">
              {t('common.appName')}
            </span>
          </div>
          <nav className="flex items-center gap-6 text-[13px]">
            <a
              href="https://github.com"
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-1.5 text-[hsl(var(--text-secondary))] transition-colors duration-200 hover:text-[hsl(var(--text-primary))]"
            >
              <svg className="h-[15px] w-[15px]" viewBox="0 0 24 24" fill="currentColor"><path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/></svg>
              {t('landing.footer.links.github')}
            </a>
            <a href="#" className="text-[hsl(var(--text-secondary))] transition-colors duration-200 hover:text-[hsl(var(--text-primary))]">
              {t('landing.footer.links.privacy')}
            </a>
            <a href="#" className="text-[hsl(var(--text-secondary))] transition-colors duration-200 hover:text-[hsl(var(--text-primary))]">
              {t('landing.footer.links.terms')}
            </a>
          </nav>
        </div>
        <div className="mt-8 border-t border-[hsl(var(--border-default))]/50 pt-8 text-center">
          <p className="text-[13px] text-[hsl(var(--text-secondary))]">{t('landing.footer.copyright')}</p>
        </div>
      </div>
    </footer>
  )
}
