// app/components/workbench/GlobalSettingsPanel.vue
<template>
  <div class="global-settings-panel p-4 space-y-4">
    <t-form label-align="top" :data="formState">
      <!-- 字体大小 -->
      <t-form-item :label="t('settings.font') + '大小'">
        <t-slider
          v-model="formState.baseFontSize"
          :min="12"
          :max="22"
          :step="1"
          show-value
          @change="commit"
        />
      </t-form-item>

      <!-- 页面边距 -->
      <t-form-item label="页面边距">
        <t-slider
          v-model="formState.pagePadding"
          :min="0"
          :max="80"
          :step="2"
          show-value
          @change="commit"
        />
      </t-form-item>

      <!-- 段落间距 -->
      <t-form-item label="段落间距">
        <t-slider
          v-model="formState.paragraphSpacing"
          :min="0"
          :max="40"
          :step="1"
          show-value
          @change="commit"
        />
      </t-form-item>

      <!-- 行高 -->
      <t-form-item label="行高">
        <t-slider
          v-model="formState.lineHeight"
          :min="1"
          :max="2.5"
          :step="0.1"
          show-value
          @change="commit"
        />
      </t-form-item>

      <!-- 模块间距 -->
      <t-form-item label="模块间距">
        <t-slider
          v-model="formState.sectionSpacing"
          :min="0"
          :max="40"
          :step="1"
          show-value
          @change="commit"
        />
      </t-form-item>

      <!-- 标题大小 -->
      <t-form-item label="标题大小">
        <t-input-number
          v-model="formState.headerSize"
          :min="14"
          :max="32"
          :step="1"
          @change="commit"
        />
      </t-form-item>

      <!-- 副标题大小 -->
      <t-form-item label="副标题大小">
        <t-input-number
          v-model="formState.subheaderSize"
          :min="12"
          :max="28"
          :step="1"
          @change="commit"
        />
      </t-form-item>

      <t-divider />

      <!-- 图标模式 -->
      <t-form-item label="使用图标模式">
        <t-switch v-model="formState.useIconMode" @change="commit" />
      </t-form-item>

      <!-- 居中副标题 -->
      <t-form-item label="居中副标题">
        <t-switch v-model="formState.centerSubtitle" @change="commit" />
      </t-form-item>

      <!-- 灵活头部布局 -->
      <t-form-item label="灵活头部布局">
        <t-switch v-model="formState.flexibleHeaderLayout" @change="commit" />
      </t-form-item>
    </t-form>
  </div>
</template>

<script setup lang="ts">
import { reactive, watch } from 'vue'
import type { GlobalSettings } from '#shared/types/resume'
import { initialGlobalSettings } from '#shared/config/initialResumeData'
import { useResumeStore } from '~/stores/resume'

const props = defineProps<{
  resumeId: string
}>()

const { t } = useI18n()
const resumeStore = useResumeStore()

// 本地副本
const formState = reactive<GlobalSettings>({ ...initialGlobalSettings })

// 从 store 同步
watch(
  () => resumeStore.activeResume?.globalSettings,
  (gs) => {
    if (gs) Object.assign(formState, gs)
  },
  { immediate: true, deep: true }
)

// 提交到 store
let commitTimer: ReturnType<typeof setTimeout> | null = null
const commit = () => {
  if (!props.resumeId) return
  if (commitTimer) clearTimeout(commitTimer)
  commitTimer = setTimeout(() => {
    resumeStore.updateGlobalSettings(props.resumeId, { ...formState })
  }, 200)
}
</script>

<style scoped>
.global-settings-panel {
  max-height: calc(100vh - 120px);
  overflow-y: auto;
}
</style>

// src/components/workbench/GlobalSettingsPanel.tsx
'use client'

import { Slider, Switch, Select } from 'antd'
import { useResumeStore, selectActiveResume } from '@/stores/resume-store'
import type { GlobalSettings } from '@/shared/types/resume'

export function GlobalSettingsPanel() {
  const activeResume = useResumeStore(selectActiveResume)
  const updateGlobalSettings = useResumeStore(s => s.updateGlobalSettings)
  const gs = activeResume?.globalSettings
  if (!gs) return null

  // 用 keyof GlobalSettings 收窄 key/value 类型，避免 any 漏类型。
  const update = <K extends keyof GlobalSettings>(key: K, value: GlobalSettings[K]) => {
    if (!activeResume) return
    updateGlobalSettings(activeResume.id, { [key]: value })
  }

  return (
    <div className="space-y-6">
      <div>
        <label className="text-sm font-medium">基础字号 ({gs.baseFontSize}px)</label>
        <Slider min={12} max={24} step={1} value={gs.baseFontSize} onChange={v => update('baseFontSize', v)} />
      </div>
      <div>
        <label className="text-sm font-medium">页面边距 ({gs.pagePadding}px)</label>
        <Slider min={16} max={64} step={4} value={gs.pagePadding} onChange={v => update('pagePadding', v)} />
      </div>
      <div>
        <label className="text-sm font-medium">标题字号 ({gs.headerSize}px)</label>
        <Slider min={14} max={36} step={1} value={gs.headerSize} onChange={v => update('headerSize', v)} />
      </div>
      <div>
        <label className="text-sm font-medium">副标题字号 ({gs.subheaderSize}px)</label>
        <Slider min={12} max={28} step={1} value={gs.subheaderSize} onChange={v => update('subheaderSize', v)} />
      </div>
      <div>
        <label className="text-sm font-medium">段落间距 ({gs.paragraphSpacing}px)</label>
        <Slider min={4} max={24} step={2} value={gs.paragraphSpacing} onChange={v => update('paragraphSpacing', v)} />
      </div>
      <div>
        <label className="text-sm font-medium">模块间距 ({gs.sectionSpacing}px)</label>
        <Slider min={4} max={32} step={2} value={gs.sectionSpacing} onChange={v => update('sectionSpacing', v)} />
      </div>
      <div>
        <label className="text-sm font-medium">行高 ({gs.lineHeight})</label>
        <Slider min={1.2} max={2.4} step={0.1} value={gs.lineHeight} onChange={v => update('lineHeight', v)} />
      </div>
      <div className="flex items-center justify-between">
        <label className="text-sm font-medium">图标模式</label>
        <Switch checked={gs.useIconMode} onChange={v => update('useIconMode', v)} />
      </div>
      <div className="flex items-center justify-between">
        <label className="text-sm font-medium">副标题居中</label>
        <Switch checked={gs.centerSubtitle} onChange={v => update('centerSubtitle', v)} />
      </div>
      <div className="flex items-center justify-between">
        <label className="text-sm font-medium">自适应一页</label>
        <Switch checked={gs.autoOnePage} onChange={v => update('autoOnePage', v)} />
      </div>
      <div>
        <label className="text-sm font-medium">字形</label>
        <Select value={gs.fontFamily || 'sans'} onChange={v => update('fontFamily', v)} style={{ width: '100%' }} options={[{value:'sans',label:'无衬线'},{value:'serif',label:'衬线'}]} />
      </div>
    </div>
  )
}
