// app/components/editor/basic/BasicInfoPanel.vue
<template>
  <div class="space-y-6 p-6">
    <!-- 布局选择 -->
    <div class="space-y-2">
      <h3 class="text-base font-medium">布局</h3>
      <t-radio-group v-model="layout" variant="default-filled" @change="handleLayoutChange">
        <t-radio-button value="left">左对齐</t-radio-button>
        <t-radio-button value="center">居中</t-radio-button>
        <t-radio-button value="right">右对齐</t-radio-button>
      </t-radio-group>
    </div>

    <!-- 照片上传 -->
    <div class="space-y-2">
      <h3 class="text-base font-medium">照片</h3>
      <div class="flex items-center gap-4">
        <div class="w-24 h-32 border rounded overflow-hidden bg-[hsl(var(--bg-base))] flex items-center justify-center">
          <img v-if="photo" :src="photo" class="w-full h-full object-cover" />
          <span v-else class="text-xs text-[hsl(var(--text-tertiary))]">无照片</span>
        </div>
        <div class="flex flex-col gap-2">
          <t-upload :show-upload-progress="false" :auto-upload="false" @select-change="handlePhotoSelect">
            <t-button theme="primary">选择照片</t-button>
          </t-upload>
          <t-button v-if="photo" theme="default" @click="removePhoto">移除</t-button>
        </div>
      </div>
      <!-- 照片配置 -->
      <div class="grid grid-cols-3 gap-3 mt-3">
        <t-form-item label="宽度">
          <t-input-number v-model="photoConfig.width" :min="50" :max="200" @change="updatePhotoConfig" />
        </t-form-item>
        <t-form-item label="高度">
          <t-input-number v-model="photoConfig.height" :min="50" :max="200" @change="updatePhotoConfig" />
        </t-form-item>
        <t-form-item label="圆角">
          <t-select v-model="photoConfig.borderRadius" @change="updatePhotoConfig">
            <t-option value="none">无</t-option>
            <t-option value="medium">中等</t-option>
            <t-option value="full">圆形</t-option>
          </t-select>
        </t-form-item>
      </div>
    </div>

    <!-- 基本信息字段 -->
    <div class="space-y-3">
      <h3 class="text-base font-medium">{{ t('resume.sections.basic') }}</h3>
      <t-form label-align="top">
        <div class="grid grid-cols-2 gap-3">
          <t-form-item :label="t('editor.basicInfo.name')">
            <t-input v-model="basicInfo.name" @blur="commitBasicInfo" />
          </t-form-item>
          <t-form-item :label="t('editor.basicInfo.title')">
            <t-input v-model="basicInfo.title" @blur="commitBasicInfo" />
          </t-form-item>
          <t-form-item :label="t('editor.basicInfo.email')">
            <t-input v-model="basicInfo.email" @blur="commitBasicInfo" />
          </t-form-item>
          <t-form-item :label="t('editor.basicInfo.phone')">
            <t-input v-model="basicInfo.phone" @blur="commitBasicInfo" />
          </t-form-item>
          <t-form-item :label="t('editor.basicInfo.location')">
            <t-input v-model="basicInfo.location" @blur="commitBasicInfo" />
          </t-form-item>
          <t-form-item :label="t('editor.basicInfo.age')">
            <t-input v-model="basicInfo.age" placeholder="28" @blur="commitBasicInfo" />
          </t-form-item>
          <t-form-item :label="t('editor.basicInfo.website')">
            <t-input v-model="personalWebsite" @blur="commitBasicInfo" placeholder="https://example.com" />
          </t-form-item>
          <t-form-item :label="t('editor.basicInfo.status')">
            <t-input v-model="basicInfo.employementStatus" @blur="commitBasicInfo" />
          </t-form-item>
        </div>
      </t-form>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { BasicInfo, PhotoConfig } from '#shared/types/resume'
import { useResumeStore } from '~/stores/resume'

const { t } = useI18n()
const resumeStore = useResumeStore()

// 本地副本，避免每次输入都触发 store 更新
const basicInfo = reactive<BasicInfo>({
  birthDate: '',
  age: '',
  name: '',
  title: '',
  email: '',
  phone: '',
  location: '',
  icons: {},
  employementStatus: '',
  photo: '',
  photoConfig: { width: 90, height: 120, aspectRatio: '1:1', borderRadius: 'none', customBorderRadius: 0, visible: true },
  customFields: [],
})

const layout = ref<'left' | 'center' | 'right'>('left')

// 从 store 同步
watch(() => resumeStore.activeResume, (resume) => {
  if (resume?.basic) {
    Object.assign(basicInfo, resume.basic)
    layout.value = resume.basic.layout || 'left'
  }
}, { immediate: true })

const commitBasicInfo = () => {
  if (!resumeStore.activeResumeId) return
  resumeStore.updateBasicInfo(resumeStore.activeResumeId, { ...basicInfo, layout: layout.value })
}

// 个人网站：复用 customFields 中 id==='personal' 的项
const personalWebsite = computed({
  get() {
    const field = basicInfo.customFields.find((f) => f.id === 'personal')
    return field?.value || ''
  },
  set(val: string) {
    const idx = basicInfo.customFields.findIndex((f) => f.id === 'personal')
    if (idx >= 0) {
      basicInfo.customFields[idx].value = val
    } else {
      basicInfo.customFields.push({
        id: 'personal',
        label: t('editor.basicInfo.website'),
        value: val,
        icon: 'Globe',
      })
    }
  },
})

const handleLayoutChange = (value: string) => {
  layout.value = value as 'left' | 'center' | 'right'
  commitBasicInfo()
}

// 照片
const photo = computed(() => basicInfo.photo)

const photoConfig = reactive<PhotoConfig>({
  width: 90,
  height: 120,
  aspectRatio: '1:1',
  borderRadius: 'none',
  customBorderRadius: 0,
  visible: true,
})

watch(() => basicInfo.photoConfig, (cfg) => {
  if (cfg) Object.assign(photoConfig, cfg)
}, { immediate: true, deep: true })

const handlePhotoSelect = (files: File[]) => {
  const file = files?.[0]
  if (!file) return
  const reader = new FileReader()
  reader.onload = (e) => {
    basicInfo.photo = e.target?.result as string
    commitBasicInfo()
  }
  reader.readAsDataURL(file)
}

const removePhoto = () => {
  basicInfo.photo = ''
  commitBasicInfo()
}

const updatePhotoConfig = () => {
  basicInfo.photoConfig = { ...photoConfig }
  commitBasicInfo()
}
</script>

// src/components/editor/basic/BasicInfoPanel.tsx
'use client'

import { useState, useEffect, useCallback } from 'react'
import { Form, Input, InputNumber, Select, Radio, Button, Upload, message } from 'antd'
import type { UploadFile } from 'antd'
import { useResumeStore, selectActiveResume } from '@/stores/resume-store'
import type { PhotoConfig } from '@/shared/types/resume'

export function BasicInfoPanel() {
  const activeResume = useResumeStore(selectActiveResume)
  const activeResumeId = useResumeStore((s) => s.activeResumeId)
  const updateBasicInfo = useResumeStore((s) => s.updateBasicInfo)

  const [form] = Form.useForm()
  const [photo, setPhoto] = useState<string>('')
  const [photoConfig, setPhotoConfig] = useState<PhotoConfig>({
    width: 90,
    height: 120,
    aspectRatio: '1:1',
    borderRadius: 'none',
    customBorderRadius: 0,
    visible: true,
  })
  const [layout, setLayout] = useState<'left' | 'center' | 'right'>('left')

  useEffect(() => {
    if (activeResume?.basic) {
      const b = activeResume.basic
      form.setFieldsValue(b)
      setPhoto(b.photo || '')
      setPhotoConfig(b.photoConfig || photoConfig)
      setLayout(b.layout || 'left')
    }
  }, [activeResume])

  const commit = useCallback(() => {
    if (!activeResumeId) return
    const values = form.getFieldsValue()
    updateBasicInfo(activeResumeId, { ...values, photo, photoConfig, layout })
  }, [activeResumeId, form, photo, photoConfig, layout, updateBasicInfo])

  const handlePhotoSelect = (file: UploadFile) => {
    const reader = new FileReader()
    reader.onload = () => {
      const base64 = reader.result as string
      setPhoto(base64)
      setTimeout(() => {
        if (activeResumeId) {
          updateBasicInfo(activeResumeId, {
            ...form.getFieldsValue(),
            photo: base64,
            photoConfig,
            layout,
          })
        }
      }, 0)
    }
    if (file.originFileObj) {
      reader.readAsDataURL(file.originFileObj)
    }
    return false
  }

  const removePhoto = () => {
    setPhoto('')
    commit()
  }

  return (
    <div className="space-y-6 p-6">
      <div className="space-y-2">
        <h3 className="text-base font-medium">布局</h3>
        <Radio.Group
          value={layout}
          onChange={(e) => {
            setLayout(e.target.value)
            setTimeout(commit, 0)
          }}
        >
          <Radio.Button value="left">左对齐</Radio.Button>
          <Radio.Button value="center">居中</Radio.Button>
          <Radio.Button value="right">右对齐</Radio.Button>
        </Radio.Group>
      </div>

      <div className="space-y-2">
        <h3 className="text-base font-medium">照片</h3>
        <div className="flex items-center gap-4">
          <div className="w-24 h-32 border rounded overflow-hidden bg-[hsl(var(--bg-base))] flex items-center justify-center">
            {photo ? (
              <img
                src={photo}
                className="w-full h-full object-cover"
                alt="简历照片"
              />
            ) : (
              <span className="text-xs text-[hsl(var(--text-tertiary))]">
                无照片
              </span>
            )}
          </div>
          <div className="flex flex-col gap-2">
            <Upload
              showUploadList={false}
              beforeUpload={handlePhotoSelect as any}
            >
              <Button>选择照片</Button>
            </Upload>
            {photo && (
              <Button onClick={removePhoto} danger>
                移除照片
              </Button>
            )}
          </div>
        </div>
        <div className="grid grid-cols-3 gap-3 mt-3">
          <div>
            <label className="text-xs text-[hsl(var(--text-secondary))]">
              宽度
            </label>
            <InputNumber
              value={photoConfig.width}
              min={50}
              max={200}
              onChange={(v) => {
                setPhotoConfig((p) => ({ ...p, width: v || 90 }))
              }}
              style={{ width: '100%' }}
            />
          </div>
          <div>
            <label className="text-xs text-[hsl(var(--text-secondary))]">
              高度
            </label>
            <InputNumber
              value={photoConfig.height}
              min={50}
              max={200}
              onChange={(v) => {
                setPhotoConfig((p) => ({ ...p, height: v || 120 }))
              }}
              style={{ width: '100%' }}
            />
          </div>
          <div>
            <label className="text-xs text-[hsl(var(--text-secondary))]">
              圆角
            </label>
            <Select
              value={photoConfig.borderRadius}
              onChange={(v) =>
                setPhotoConfig((p) => ({ ...p, borderRadius: v }))
              }
              style={{ width: '100%' }}
              options={[
                { value: 'none', label: '无' },
                { value: 'medium', label: '中等' },
                { value: 'full', label: '圆形' },
              ]}
            />
          </div>
        </div>
      </div>

      <div className="space-y-3">
        <h3 className="text-base font-medium">基本信息</h3>
        <Form form={form} layout="vertical" onBlur={commit}>
          <div className="grid grid-cols-2 gap-3">
            <Form.Item name="name" label="姓名">
              <Input placeholder="请输入姓名" />
            </Form.Item>
            <Form.Item name="title" label="职位">
              <Input placeholder="请输入职位" />
            </Form.Item>
            <Form.Item name="email" label="邮箱">
              <Input placeholder="请输入邮箱" />
            </Form.Item>
            <Form.Item name="phone" label="电话">
              <Input placeholder="请输入电话" />
            </Form.Item>
            <Form.Item name="location" label="所在地">
              <Input placeholder="请输入所在地" />
            </Form.Item>
            <Form.Item name="age" label="年龄">
              <Input placeholder="28" />
            </Form.Item>
            <Form.Item name="employementStatus" label="状态">
              <Input placeholder="在职/离职/应届" />
            </Form.Item>
          </div>
        </Form>
      </div>
    </div>
  )
}
