// app/components/editor/custom/CustomItem.vue
<template>
  <div class="border border-[hsl(var(--border))] rounded-md mb-2">
    <!-- 折叠头 -->
    <div class="flex items-center gap-2 p-3 bg-[hsl(var(--muted))]">
      <button class="drag-handle cursor-move text-gray-400 hover:text-gray-600" title="拖动排序">
        <GripVertical class="w-4 h-4" />
      </button>
      <t-button variant="text" size="small" @click="collapsed = !collapsed">
        <ChevronDown v-if="collapsed" class="w-4 h-4" />
        <ChevronUp v-else class="w-4 h-4" />
      </t-button>
      <div class="flex-1 truncate">
        <span class="font-medium">{{ local.title || '未填写标题' }}</span>
        <span v-if="local.subtitle" class="text-gray-500 ml-2">· {{ local.subtitle }}</span>
      </div>
      <t-tooltip content="可见性">
        <t-switch v-model="local.visible" size="small" @change="commit" />
      </t-tooltip>
      <t-tooltip content="删除">
        <t-button variant="text" size="small" theme="danger" @click="emit('remove')">
          <Trash2 class="w-4 h-4" />
        </t-button>
      </t-tooltip>
    </div>

    <!-- 展开内容 -->
    <div v-show="!collapsed" class="p-4 space-y-3">
      <t-form label-align="top">
        <div class="grid grid-cols-2 gap-3">
          <t-form-item label="标题">
            <t-input v-model="local.title" @blur="commit" />
          </t-form-item>
          <t-form-item label="副标题">
            <t-input v-model="local.subtitle" @blur="commit" />
          </t-form-item>
          <t-form-item label="日期范围">
            <t-input v-model="local.dateRange" placeholder="2020.01 - 2021.01" @blur="commit" />
          </t-form-item>
        </div>
      </t-form>
      <!-- 描述富文本 -->
      <div class="space-y-2">
        <div class="text-sm font-medium">描述</div>
        <EditorToolbar :editor="editor" />
        <TiptapEditor v-model="local.description" />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { CustomItem } from '#shared/types/resume'
import { GripVertical, ChevronDown, ChevronUp, Trash2 } from 'lucide-vue-next'
import { useEditor } from '@tiptap/vue-3'
import StarterKit from '@tiptap/starter-kit'
import Underline from '@tiptap/extension-underline'
import TextAlign from '@tiptap/extension-text-align'
import Placeholder from '@tiptap/extension-placeholder'
// @tiptap/extension-text-style@3.x 仅提供命名导出，无默认导出
import { TextStyle } from '@tiptap/extension-text-style'
import Color from '@tiptap/extension-color'
import Highlight from '@tiptap/extension-highlight'
import Link from '@tiptap/extension-link'

const props = defineProps<{ item: CustomItem }>()
const emit = defineEmits<{ update: [data: Partial<CustomItem>]; remove: [] }>()

const local = reactive<CustomItem>({ ...props.item })
const collapsed = ref(false)

watch(() => props.item, (item) => {
  Object.assign(local, item)
}, { deep: true })

const commit = () => {
  emit('update', { ...local })
}

const editor = useEditor({
  content: local.description || '',
  extensions: [
    StarterKit,
    Underline,
    TextStyle,
    Color,
    Highlight,
    Link.configure({ openOnClick: false }),
    TextAlign.configure({ types: ['heading', 'paragraph'] }),
    Placeholder.configure({ placeholder: '请输入描述...' }),
  ],
  onUpdate: ({ editor }) => {
    local.description = editor.getHTML()
    commit()
  },
})

watch(() => local.description, (val) => {
  if (editor.value && val !== editor.value.getHTML()) {
    editor.value.commands.setContent(val || '', false)
  }
})

onBeforeUnmount(() => {
  editor.value?.destroy()
})
</script>

// src/components/editor/custom/CustomItem.tsx
'use client'

import { Input } from 'antd'
import { Trash2 } from 'lucide-react'
import type { CustomItem as CustomItemType } from '@/shared/types/resume'

interface CustomItemProps {
  item: CustomItemType
  sectionId: string
  onChange: (
    sectionId: string,
    itemId: string,
    data: Partial<CustomItemType>
  ) => void
  onDelete: (sectionId: string, itemId: string) => void
}

export function CustomItem({
  item,
  sectionId,
  onChange,
  onDelete,
}: CustomItemProps) {
  return (
    <div className="border rounded-lg p-4 space-y-3 bg-[hsl(var(--bg-elevated))]">
      <div className="grid grid-cols-2 gap-3">
        <Input
          value={item.title}
          placeholder="标题"
          onChange={(e) =>
            onChange(sectionId, item.id, { title: e.target.value })
          }
        />
        <Input
          value={item.subtitle}
          placeholder="副标题"
          onChange={(e) =>
            onChange(sectionId, item.id, { subtitle: e.target.value })
          }
        />
      </div>
      <Input
        value={item.dateRange}
        placeholder="时间范围 (如 2020-2023)"
        onChange={(e) =>
          onChange(sectionId, item.id, { dateRange: e.target.value })
        }
      />
      <Input.TextArea
        value={item.description}
        placeholder="描述"
        rows={4}
        onChange={(e) =>
          onChange(sectionId, item.id, { description: e.target.value })
        }
      />
      <div className="flex justify-end">
        <button
          type="button"
          className="inline-flex items-center gap-1 text-sm text-red-500 hover:text-red-600 transition-colors"
          onClick={() => onDelete(sectionId, item.id)}
        >
          <Trash2 className="w-4 h-4" />
          删除
        </button>
      </div>
    </div>
  )
}
